spring:  data:    mongodb:      cluster: localhost:27017, localhost:27018, localhost:27019      authentication-database: admin      username: root      password: P@ssw0rd      database: kakao  servlet:    multipart:      max-file-size: 100MB      max-request-size: 100MB  
coupon:
  section-size:
    first: 5
    second: 6
    third: 8
  delimiter: '-'
  csv-path: '/csv'  default-expire-day: 7
