version: '2.2'

services:
  mongo_01:
    container_name: mongo_01
    image: mongo:4.2.7
    ports:
      - 27017:27017
    environment:
      - TZ=Asia/Seoul   
    command: mongod --replSet mongo-repl
    networks:
      - mongo_net
  mongo_02:
    container_name: mongo_02
    image: mongo:4.2.7
    ports:
      - 27018:27017
    environment:
      - TZ=Asia/Seoul
    command: mongod --replSet mongo-repl
    networks:
      - mongo_net
  mongo_03:
    container_name: mongo_03
    image: mongo:4.2.7
    ports: 
      - 27019:27017
    environment:
      - TZ=Asia/Seoul
    command: mongod --replSet mongo-repl
    networks:
      - mongo_net

networks:
  mongo_net:
    external:
      name: mongo_net
