version: '2.2'

services:
  mongo:
    container_name: mongo
    image: mongo:4.2.7
    ports:
      - 27017:27017
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=root"
      - "MONGO_INITDB_ROOT_PASSWORD=P@ssw0rd"
